import{a as L,i,S as b}from"./assets/vendor-tnUJPedx.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const v="https://pixabay.com/api/",w="47428851-5b047435bdffa798507e52955";async function g(t,o=1,s=15){return(await L.get(v,{params:{key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:s}})).data}function m(t){return t.map(({webformatURL:o,largeImageURL:s,tags:n,likes:e,views:r,comments:a,downloads:y})=>`
        <li>
          <a href="${s}">
            <img src="${o}" alt="${n}" loading="lazy" />
          </a>
          <div class="gallery-item-info">
            <span>Likes: ${e}</span>
            <span>Views: ${r}</span>
            <span>Comments: ${a}</span>
            <span>Downloads: ${y}</span>
          </div>
        </li>`).join("")}const S=document.querySelector("#search-form"),l=document.querySelector(".gallery"),d=document.querySelector("#load-more"),q=document.querySelector(".loader");let c="",u=1,h=0,p;S.addEventListener("submit",x);d.addEventListener("click",T);async function x(t){if(t.preventDefault(),c=t.currentTarget.searchQuery.value.trim(),!c){i.warning({message:"Please enter a search query!"});return}u=1,l.innerHTML="",f(!0),d.classList.add("hidden");try{const{hits:o,totalHits:s}=await g(c,u);if(h=s,o.length===0){i.info({message:"No results found."});return}l.innerHTML=m(o),$(),h>o.length&&d.classList.remove("hidden")}catch{i.error({message:"Failed to fetch images. Try again later."})}finally{f(!1)}}async function T(){u+=1,f(!0);try{const{hits:t}=await g(c,u);l.insertAdjacentHTML("beforeend",m(t)),E(),l.children.length>=h&&(d.classList.add("hidden"),i.info({message:"We're sorry, but you've reached the end of search results."}))}catch{i.error({message:"Failed to load more images."})}finally{f(!1),H()}}function f(t){q.classList.toggle("hidden",!t)}function $(){p=new b(".gallery a")}function E(){p.refresh()}function H(){const{height:t}=l.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
